# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'BLOG'
tagline:          'Davis Blog'
description:      'Hey! I&#39;m <a href="http://daviskr.com/">Davis</a>, and this is my blog!'
url:              http://daviskr.com/blog/
baseurl:          /blog 

author:
  name:           'Davis Robertson'
  url:            http://daviskr.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/epicdavi/blog/
